### ISSUE TITLE
Adding a hover effect to profile image and added my profile

### ISSUE THREAD

**Issue by Mudasir7-Prof-Snape** [oyepriyansh/DevProfiles#108]
![Screenshot from 2023-10-05 13-15-47](https://github.com/oyepriyansh/DevProfiles/assets/140256749/50712def-a24e-4991-b55d-d84bd641fca0)

**Comment by oyepriyansh** [comment]
Assigned to you

**Comment by Neeraaaj** [comment]
@oyepriyansh hey, if the issue is still not fixed assign it to me!

**Comment by ojKunal** [comment]
I would like to work on this issue . Please assign this issue to me.
