### ISSUE TITLE
Improve Code Structure 

### ISSUE THREAD

**Issue by harshal255** [oyepriyansh/DevProfiles#111]
## Improve Code Structure 
- make a JSON file for the developer's profiles & use the es6+ method (like a map for displaying all profile details in index.js).
- improve read.md file related to task 1
- so, the user can easily put data in json file instead of doing this hard-coding...

**Comment by harshal255** [comment]
yeah sure

**Comment by oyepriyansh** [comment]
Nice idea

**Comment by harshal255** [comment]
> Nice idea

hello brother, why am I getting this (excluded)
![image](https://github.com/oyepriyansh/DevProfiles/assets/93152436/4018b2b2-23e2-4552-b025-060bdf6be808)
