### ISSUE TITLE
adding navbar in DevProfiles main page

### ISSUE THREAD

**Issue by Altair-05** [oyepriyansh/DevProfiles#120]
@oyepriyansh, I'm interested in taking on the task of adding a navbar to the main page. 
Could you please assign it to me?

**Comment by Neeraaaj** [comment]
@oyepriyansh, assign me this i think i can make this work

**Comment by oyepriyansh** [comment]
assigned to you

**Comment by SyntaxSmiler03** [comment]
thankyou @oyepriyansh ..
