### ISSUE TITLE
Login And Signup page

### ISSUE THREAD

**Issue by Raghu1124** [oyepriyansh/DevProfiles#144]
hey! I think it can have a basuc login-signup page, and i want to work on it, please assign me this issue and make it hactoberfest acceptable

**Comment by oyepriyansh** [comment]
We want people to contribute their profiles via GitHub rather than through the web interface, as it is intended for developers.

**Comment by AniketP04** [comment]
I'm willing to work on this issue and collaborate with the maintainers. Please let me know how I can proceed.
