### ISSUE TITLE
Suggestion to Improve the hover and shadow effect 

### ISSUE THREAD

**Issue by amrahs02** [oyepriyansh/DevProfiles#175]
I think this look good, but I can make even better hover and shadow effect 
Without Hover:
![Screenshot from 2023-10-07 16-42-59](https://github.com/oyepriyansh/DevProfiles/assets/65103353/5b22fd94-9d52-436a-a763-2b3c1af67f6a)
On Hover:
![Screenshot from 2023-10-07 16-43-08](https://github.com/oyepriyansh/DevProfiles/assets/65103353/a9e46f13-22f3-482a-8f20-10b5502fb093)

**Comment by amrahs02** [comment]
can you assign this to me?

**Comment by oyepriyansh** [comment]
> can you assign this to me?

assigned to you.
