### ISSUE TITLE
dark mode text not properly visible.

### ISSUE THREAD

**Issue by Neeraaaj** [oyepriyansh/DevProfiles#177]
the button color is black, also the text inside is also black which makes the UI look not so good

![dark_mode_issue](https://github.com/oyepriyansh/DevProfiles/assets/110386298/927ea3d9-9088-432a-8709-adee35884547)

**Comment by oyepriyansh** [comment]
it is not

![image](https://github.com/oyepriyansh/DevProfiles/assets/83062406/80c13940-c9d4-4dae-8321-89a140af98a6)

**Comment by Neeraaaj** [comment]
you have to change the theme from white to dark then the glitch will appear

**Comment by Neeraaaj** [comment]
@oyepriyansh

**Comment by oyepriyansh** [comment]
alright
