### ISSUE TITLE
Bug: Error in GitHub profile URL

### ISSUE THREAD

**Issue by bilalmirza74** [oyepriyansh/DevProfiles#185]
### Description

#183

### Screenshots

![image](https://github.com/oyepriyansh/DevProfiles/assets/84387676/705969d1-ec05-48de-814f-6acba0eba544)

![image](https://github.com/oyepriyansh/DevProfiles/assets/84387676/e127b4a8-21b2-4ce4-a99f-3c1a8b4283e7)

### Ready to Work?

- [X] I want to work on this issue

**Comment by Neeraaaj** [comment]
it's because the username might be changed

**Comment by oyepriyansh** [comment]
assigned to you
