### ISSUE TITLE
Bug: Overflow of Toggle Dark Mode Button

### ISSUE THREAD

**Issue by Pinaka-Pani-18** [oyepriyansh/DevProfiles#203]
### Description

There is an overflow issue with the dark mode button, as you can see in the video below.

I want to work on this issue. If possible, could you label it as "Hacktoberfest"? It would be helpful.

### Screenshots

https://github.com/oyepriyansh/DevProfiles/assets/102857774/9bf866da-aade-457b-8c5c-83d4afe5769e

### What browsers are you seeing the problem on?

Chrome, Firefox, Microsoft Edge

### Ready to Work?

- [X] I want to work on this issue

**Comment by WilliamDavidHarrison** [comment]
I've assigned you. Your PR, once merged, will be labelled as hacktoberfest-accepted.

**Comment by Pinaka-Pani-18** [comment]
> I've assigned you. Your PR, once merged, will be labelled as hacktoberfest-accepted.

I have submitted the pull request for this issue. Please review it
