### ISSUE TITLE
Revamp Footer Section for Improved Professionalism

### ISSUE THREAD

**Issue by dev31sanghvi** [oyepriyansh/DevProfiles#222]
I would like to propose a revamp of the current footer section to make it more visually appealing and professional. 

here is the picture with the changes :
![Screenshot from 2024-01-19 20-57-43](https://github.com/oyepriyansh/DevProfiles/assets/105737978/c9d2c6f2-cb4e-4d33-9e95-1b3a37839826)

**Comment by oyepriyansh** [comment]
@dev31sanghvi assigned to you!

**Comment by dev31sanghvi** [comment]
@oyepriyansh PR raised !
