### ISSUE TITLE
feat:Add a Back to top FAB

### ISSUE THREAD

**Issue by FazeenIjaz** [oyepriyansh/DevProfiles#229]
### Description

currently, there is no mechanism to go back to the top and the user has to manually scroll back to top. I would like to add a back-to-top FAB.
@oyepriyansh pls assign it to me

### Ready to Work?

- [x] I want to work on this issue

**Comment by oyepriyansh** [comment]
@FazeenIjaz assigned to you

**Comment by FazeenIjaz** [comment]
@oyepriyansh I had raised a PR, please check it out
