### ISSUE TITLE
feat:Make header sticky for better UI

### ISSUE THREAD

**Issue by FazeenIjaz** [oyepriyansh/DevProfiles#231]
### Description

currently, header has static position , It should be sticky so that it shows up even if scrolling the page

Pls assign it to me @oyepriyansh 

### Screenshots

Current behaviour

![image](https://github.com/oyepriyansh/DevProfiles/assets/144797618/6e88195b-1fef-434a-b967-9d71b1865025)

Desired behavior 

![image](https://github.com/oyepriyansh/DevProfiles/assets/144797618/40ba6230-812b-44cf-bad9-db3b7eef6692)

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
@FazeenIjaz assigned to you

**Comment by FazeenIjaz** [comment]
@oyepriyansh I had raised a PR, pls check it out
