### ISSUE TITLE
Typos and unformatted html file

### ISSUE THREAD

**Issue by FazeenIjaz** [oyepriyansh/DevProfiles#234]
### Description

Typo in contributing.md and readme

### Screenshots

![image](https://github.com/oyepriyansh/DevProfiles/assets/144797618/913e8f9c-afb0-4ee2-8a6c-31e96f30d358)

![image](https://github.com/oyepriyansh/DevProfiles/assets/144797618/fbc04440-10c1-4216-9c57-88fb58f9d985)

![image](https://github.com/oyepriyansh/DevProfiles/assets/144797618/f63a90a6-99ca-4c01-9de1-361ebe52d092)

![image](https://github.com/oyepriyansh/DevProfiles/assets/144797618/ec4a2743-c70f-41b3-8ed2-bf488e56c522)

I would like to fix it, pls assign it

### Ready to Work?

- [X] I want to work on this issue

**Comment by FazeenIjaz** [comment]
@oyepriyansh I had raised a PR. please check  it out

**Comment by oyepriyansh** [comment]
sorry but there is no need to format the current html file, and those are not typos
