### ISSUE TITLE
feat: pagination

### ISSUE THREAD

**Issue by shreyashaw05** [oyepriyansh/DevProfiles#238]
### Description

Since there are many devlopers listed here it will be diffiicult for one to scroll throughout the page so pagination would be proved very helpful for it...

### Ready to Work?

- [X] I want to work on this issue

**Comment by oyepriyansh** [comment]
If we add pagination, no one will want to add their profile on the page rather than the main page because of publicity. So, I think that's not a good idea.

**Comment by shreyashaw05** [comment]
> If we add pagination, no one will want to add their profile on the page rather than the main page because of publicity. So, I think that's not a good idea.

ok

**Comment by shreyashaw05** [comment]
ok
