### ISSUE TITLE
Missing Block of Code in index.html file

### ISSUE THREAD

**Issue by RushikeshShelar** [oyepriyansh/DevProfiles#28]
There is Missing block of Code in the ``` index.html ``` file at line no 180.
![image](https://github.com/oyepriyansh/DevProfiles/assets/112684561/063c70be-b097-43cd-baea-8bddec757d27)

A Closing </div> Tag is missing for the Social Links. That Results in the Break Down of the User Interface Causing it to look like a Long Single Card As follows:

![Screenshot (60)](https://github.com/oyepriyansh/DevProfiles/assets/112684561/8c6eb253-9bca-4475-b441-b68baa7f9c15)
![Screenshot (61)](https://github.com/oyepriyansh/DevProfiles/assets/112684561/83a18f2a-4516-465b-90f1-c0eaf931e138)

**Comment by RushikeshShelar** [comment]
I have Fixed this Issue And Would Like to Submit a PR for the Same

**Comment by oyepriyansh** [comment]
thank you @RushikeshShelar but it has been already fixed.
