### ISSUE TITLE
Enhance : User experience in search

### ISSUE THREAD

**Issue by mathanraj0601** [oyepriyansh/DevProfiles#49]
# Enhance user experience
When we search for a name that is not in the profile. it simply shows a blank space.

![image](https://github.com/oyepriyansh/DevProfiles/assets/98396468/c214837e-9c9a-4f73-886d-3b8efe6abd8d)

Instead, we can add the text "no profile found" below the search bar.

**Comment by mathanraj0601** [comment]
If you like the above suggestion. I like to contribute : )

**Comment by oyepriyansh** [comment]
assigned to you.

**Comment by mathanraj0601** [comment]
Thank you! can you add it for hacktoberfest

**Comment by oyepriyansh** [comment]
Done
