### ISSUE TITLE
add: contribution docs and readme decor

### ISSUE THREAD

**Issue by oyepriyansh** [oyepriyansh/DevProfiles#67]
- Create a Contributing.md file
- Decorate the readme.md and add more information 

if anyone want to work on this issue just comment below

**Comment by ira-mane** [comment]
Hello ,Can you please assign me this ? I want to work on this .
Thankyou.

**Comment by oyepriyansh** [comment]
> Hello , @oyepriyansh Can you please assign me this ? I want to work on this . Thankyou.

assigned 👍

**Comment by ira-mane** [comment]
> > Hello , @oyepriyansh Can you please assign me this ? I want to work on this . Thankyou.
> 
> assigned 👍
Thankyou ! Can you please put this under hacktober-accepted label.

**Comment by oyepriyansh** [comment]
> > > Hello , @oyepriyansh Can you please assign me this ? I want to work on this . Thankyou.
> > 
> > 
> > assigned 👍
> 
> Thankyou ! Can you please put this under hacktober-accepted label.

done

**Comment by ira-mane** [comment]
Also ,I can see you have added how one can contribute in the readme file , I will change that I will add it in the contributing.md file .
And I will update readme file. 
Also one can contribute by adding their profile ??

**Comment by oyepriyansh** [comment]
> Also ,I can see you have added how one can contribute in the readme file , I will change that I will add it in the contributing.md file . And I will update readme file. Also one can contribute by adding their profile ??

contribution guide is in readme file so you can improve it, and yes anyone can contribute by adding their profile

**Comment by ira-mane** [comment]
Hello can you please review pr
