### ISSUE TITLE
Adding footer to the website 

### ISSUE THREAD

**Issue by Vansh16aug** [oyepriyansh/DevProfiles#70]
a footer containing all the important information 
# pls mark it under hacktoberfest-accepted and hacktoberfest label

**Comment by oyepriyansh** [comment]
assigned to you

**Comment by Vansh16aug** [comment]
thnks

**Comment by Mafildo** [comment]
if I contribute on this project, will that be counted on hacktoberfest? 


Newbie :(

**Comment by Mafildo** [comment]
I want to make the footer section!

**Comment by oyepriyansh** [comment]
> if I contribute on this project, will that be counted on hacktoberfest? I want to make the footer section!
> 
> Newbie :(

yes, your contribution in this repository will be counted in hacktoberfes
2nd this issue is already assigned to @Vansh16aug , if they dont able to do it then i will assign you.

**Comment by Mafildo** [comment]
are there any other issues that I can work on related to html css or react?

**Comment by Raghu1124** [comment]
Can you plz assign me this issue, if someone is working already then please assign me any other issue
