### ISSUE TITLE
Improved UI: Adding light mode and other css improvements

### ISSUE THREAD

**Issue by CharithaCS** [oyepriyansh/DevProfiles#79]
I can add light mode to the website and improve UI. Please assign me this under Hacktober Fest. PS: I'm a beginner. Thanks!

**Comment by oyepriyansh** [comment]
assigned to you @CharithaCS

**Comment by CharithaCS** [comment]
Thanks! Will do it

**Comment by CharithaCS** [comment]
I have made the changes and created a PR. Kindly check
