### ISSUE TITLE
i want to add navbar..

### ISSUE THREAD

**Issue by pankajsingh92533** [oyepriyansh/DevProfiles#93]
i want to change in UI/UX to make the system more user-friendly,
I want to add trademark, searching, inside navbar.
so please assign me this issue under hacktoberfest 2023 label.

**Comment by oyepriyansh** [comment]
Assigned to you!

**Comment by pankajsingh92533** [comment]
![Uploading dev.png…]()
i have made changes..

**Comment by oyepriyansh** [comment]
please show me
