### ISSUE TITLE
Adding New Profile.

### ISSUE THREAD

**Issue by rohandol112** [oyepriyansh/DevProfiles#99]
Adding new profile named as (Rohan Dol)

**Comment by SyntaxSmiler03** [comment]
hello @oyepriyansh  
I would like to work on this same issue
could you plz assign me this task?

**Comment by SyntaxSmiler03** [comment]
under HACKTOBERFEST 2023

**Comment by oyepriyansh** [comment]
> hello @oyepriyansh I would like to work on this same issue could you plz assign me this task?

You can create a new issue
